# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('organizer', models.CharField(blank=True, max_length=256)),
                ('website', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('start_time', models.CharField(blank=True, max_length=256)),
                ('end_time', models.CharField(blank=True, max_length=256)),
                ('cost', models.CharField(blank=True, max_length=256)),
                ('venue_name', models.CharField(blank=True, max_length=256)),
                ('venue_street_address', models.CharField(blank=True, max_length=256)),
                ('venue_city', models.CharField(blank=True, max_length=256)),
                ('venue_state', models.CharField(blank=True, max_length=256)),
                ('venue_zipcode', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
